### PR TITLE
Uxprod 2564

### PR DESCRIPTION
**Pull request by EstebanSM**
## Purpose

- Redesign search panel as the inventory search panel ([UICAT-111](https://issues.folio.org/projects/UICAT/issues/UICAT-111))

- Resize panels, sometimes panels are cut and is not possible to resize ([UICAT-110](https://issues.folio.org/projects/UICAT/issues/UICAT-110))

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Comment by ryandberger** [comment]
Can you please describe the purpose of this PR? Even copy/paste of what you put in the CHANGELOG would be helpful.

**Comment by EstebanSM** [comment]
Changes made:

- Redesign search panel as the inventory search panel (UICAT-111)

- Resize panels, sometimes panels are cut and is not possible to resize (UICAT-110)

**Comment by ryandberger** [comment]
> Changes made:
> 
> * Redesign search panel as the inventory search panel (UICAT-111)
> * Resize panels, sometimes panels are cut and is not possible to resize (UICAT-110)

Can you put this in the main PR description? Sorry for being picky, but it makes a big difference 😄

**Comment by EstebanSM** [comment]
> > Changes made:
> > 
> > * Redesign search panel as the inventory search panel (UICAT-111)
> > * Resize panels, sometimes panels are cut and is not possible to resize (UICAT-110)
> 
> Can you put this in the main PR description? Sorry for being picky, but it makes a big difference 😄

ok, I understand.
I have updated it.

**Review by ryandberger — APPROVED** [review]

**Pull request merged**
